baseURL = "https://dtest11.github.io/"
languageCode = "en-us"
title = "hello"
theme = "vitae"

[menu]
  [[menu.main]]
    identifier = "go"
    name       = "GO"
    url        = "/golang/"
  [[menu.main]]
    identifier = "k8s"
    name       = "k8s"
    url        = "/k8s/"
  [[menu.main]]
    identifier = "mysql"
    name       = "mysql"
    url        = "/mysql/"
  [[menu.main]]
    identifier = "redis"
    name       = "redis"
    url        = "/redis/"
  [[menu.main]]
    identifier = "git"
    name       = "Check on github"
    url        = "https://github.com/dtest11/dtest11.github.io/"

  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts/"